os:
  - linux
  - osx

language: c

sudo: required

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker pull jchodera/omnia-build-box;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run
        -e ANACONDA_TOKEN
        -e AWS_ACCESS_KEY_ID
        -e AWS_SECRET_ACCESS_KEY
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_BRANCH
        -t -i --rm -v
        `pwd`:/io jchodera/omnia-build-box:latest
        bash /io/devtools/docker-build.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        bash devtools/osx-build.sh;
    fi

env:
  global:
    # ANACONDA_TOKEN
    - secure: "HekhZj4dA5RCTysq6PoW0gjg2prGi+bjT4bWpCf4jjl/XjDJMtVvpDjYJZSiedFZxTT3y7DoslvAXBjvSmV4o8L8zGjRT6GS+z8Nht1JDvUD6LQI+bEtHXUo9eqQZo5GW8KxKVBz6Y2lMcFPQyE3WokGcG7GzqAnh1cGLZT2XUjdgkAewQ9TU54EP8wzirNWZZXM70qei/E/3w+ISmoSoGLbppiJUfV64xNvXj7Yji2gCbPiUSCvv+ffPzDUPONC0Ia9SujtXIpeZyENpvfgXj5opgrU4Wrn8SiLX9IdKQ6SBUE1O5Lpo+Wu5QYQFnDyA9/GSqCss+EOzrEVs4ODALEgfuG3N56R6zham+JyeLkjz+3JdXn+4SYUKGjgqReP4XnarunqkoBD4DZPaMST5lLBuv6UFLl53mYqYwxEtUD9pZEM13F8WKLdLf9BgO+SokZK9ewj9gP0C1gi58J1UA+L7s7Hh4lk2elxKHAP+d41tqgL16frGYiXFsRe/Aivb5lgdqmTDPowXx253HmXvib6XurvobWWYuBCih2bYmRHnMJYha/60NgzU9AwaY/xuXOJ8391dcXUGVHIWPAQPVMu32tp/xCgV/L1ErR6Smzot6+MV03iBOL+e1Gn+o+4Ek3ZxU2mfMF3M9ksMDyYqXDo0K/N+ybqgs+FxLsRFYk="
    # AWS_ACCESS_KEY_ID
    - secure: "gfO31dVb51AF57mNXv/scm7PeF3RMVM6B3ORhRTp2iLfL1cqtLEFF164zyVRIP7sYrV17fL1jsUmm10KmGuDfSYx5N0paiEjHJ0usZMqzHm81EQ9+cjlkjjQsZULqTRzxiQ7M51hyp8n5aR/KeVS23JRHkLR8eDOGQW3X/TJNbVQi/gSM+SgsS2p4w5zAGKG8iIzJ4VFjJVRcfkhrA5WGzDq0lxoXzksOoXRCyT7gQnZfYk3xowvtOzSgUGOkaFieVpbYHgpmDAtYxf2PyPl70RMmBy4/F3Z0NANmaoA211gVXkJwHERXp7P7Y5rix8Mxy5u0A4zJZbyaqQk0QbISomRclGrN9IvZqY3rfLcZ4RK/g6hDkQkxiM2UFmTO+ohNKRT3jdVJ5g5aDdqrNYg2LeOAjhW/J55VMqh5TUfIt69nU+DDxV7s1WkowDKcaF+nPVpWcmSkjsd8W2NnKdjv+BEHucaAvnTk/N9Tafl0BA3DsXXo7pey1zbNjf9pVFaitWjVO8NlIrI+DI8bMrID4c5Gz5ihtHwyu01ilzsNEatPVfksGVn4hhI6quQc9UTNAp3JxnViCqlPp1pt2vOJwjZcufEQwfDcY4oxv0g1hG+axKh7l6yv5vSOLcConEayulXD56yhkpTaoEn2OVTZheq93pbqMfbNWqSOTZNmcs="
    # AWS_SECRET_ACCESS_KEY
    - secure: "ROndXskAuT4fA1mIgvy5j/y5m471Xy5RmPmf6L4bmjoZG98eCRBnbiIA30S7IAG1SY17g5KezZI1x48NhLos8Ika+1OeEV3ghZ2Amn90/6M+9gl+W3ufY5f+k0dujKU5ahOBzyuym7DMEduWjIfz9yfn1f2kXr0XPBUNluamlvh0NcHZgruU1lQ0xWXN46hedNSARIzovtxJBZvW/Ff27Pef4YGJg8eVnKCj5PsPUI9pgcbm5Q/sqYnqEG8fJCpQt7liQzDNm2DHmbsEF9AHcteYk0UYL5A42LOUD+KFJIguDQ9oew23k7Uj38qejNy7988l44SmVtwzLCrwlSf1PO++npYK04DE7B9rn+MZveqgIBK2CKJ/Wtp5E67LHHMLmYTlq2wAmDOuaNgY5tdH42yoB9oDImCYtuYeoDtDZP2gd6blEJYIUK5PffekFUaWCMVzG7AzUIQzt23CaiN/shLNbZEx5YEsjvxdQQzWvzjJeq7TwYyuyJPy7MFD8ldjptoW6GmfH96BgqDcQWvIHOLN5iecA45+9V2VnxtKxp5GQi0uyrnwSYc5XDuf+7bmmFqYyggX90/5tWhMk0BtLkusGJX4L2G7sL3S/phqRXqQiVh6M8L6DgGSBSi7//VU5hDIqEGKs7cKQhWA3hPFxdaahd0D6AUmH4yB4il0Dyo="

